Improve developer experience
TeamGraphix/graphix pull request #230
Opened 2024-11-01 08:32 UTC by EarlMilktea

**Description of the change:**

- List all the CI configs. in `noxfile.py`
- Setup pre-commit

2024-11-01 14:14 UTC, thierry-martinez requested changes
Thanks. Some minor remarks.

2024-11-01 14:14 UTC, thierry-martinez commented on graphix/sim/density_matrix.py
> +        assert i < self.nqubit
```suggestion
        assert 0 <= i < self.nqubit
```

2024-11-04 13:48 UTC, shinich1 reviewed
thanks! could you add instruction to use `pre-commit` in `CONTRIBUTING.md`? brief description with pointing to a good online page is ok. anything else we need to elaborate in the contribution guide?

2024-11-04 15:22 UTC, EarlMilktea commented
`CONTRIBUTING.md` is already updated to use `pre-commit` instead of `ruff`  (may need to add more though).

2024-11-04 16:51 UTC, shinich1 approved these changes

2024-11-10 11:16 UTC, EarlMilktea commented
@thierry-martinez

2024-11-26 13:11 UTC, thierry-martinez requested changes
There is a regression in `to_qasm3`, and some minor remarks.

2024-11-27 16:53 UTC, EarlMilktea commented on graphix/device_interface.py
> +            except Exception:  # noqa: BLE001
I strongly agree with you, but also I'm afraid that we anyway need thorough refactor here (so `TODO` essentially do nothing, issue is better?)

2024-11-27 17:01 UTC, EarlMilktea commented on .pre-commit-config.yaml
> +        args: [--fix, --select, I]
> When executed as a GitHub Action, messages for fixed errors are hidden, rendering the output unhelpful.
> When executed locally, making changes to the unstaged area during a commit operation is counterintuitive. Developers are better off explicitly running ruff --fix to apply auto-fix changes when errors are reported.

Agree, but if so I feel `pre-commit` may not be the best choice as its strength comes from env. isolation feature (it does not contaminate venv with CI deps.) while your comments suggest that we'd better invoke `ruff` manually by hand.

2024-11-27 17:05 UTC, EarlMilktea commented on .pre-commit-config.yaml
> +      - id: ruff
This mimics the default behavior of `isort`.

2025-01-06 13:22 UTC, thierry-martinez commented on .pre-commit-config.yaml
> +        args: [--fix, --select, I]
We can have the best of both worlds: `pre-commit` is useful for running local checks automatically and ensuring consistency with CI, while manually running `ruff --fix` is helpful for applying trivial fixes quickly. Under the rules proposed in this PR, developers would still need to invoke `ruff --fix` to automatically address errors outside the `I` group.

I believe it’s best to start with the single hook below, which offers clearer error messages and fewer surprises, and then leave room for further improvements if we later agree on additional hooks.
```
      - id: ruff
```

2025-01-06 13:24 UTC, thierry-martinez commented on .pre-commit-config.yaml
> +      - id: ruff
This thread is related to the above discussion: https://github.com/TeamGraphix/graphix/pull/230#discussion_r1904146414

2025-01-06 13:24 UTC, thierry-martinez commented on CONTRIBUTING.md
>  and you are ready to commit the changes.
This thread is related to the above discussion: https://github.com/TeamGraphix/graphix/pull/230#discussion_r1904146414

2025-01-06 13:52 UTC, thierry-martinez commented on graphix/device_interface.py
> +            except Exception:  # noqa: BLE001
I just opened a PR on this specific issue: https://github.com/TeamGraphix/graphix/pull/241 . I resolve this conversation.

2025-01-25 14:36 UTC, EarlMilktea commented
Let me close this PR as I no longer feel this PR will contribute to better DX.

2025-01-25 14:36 UTC, closed without merging